# Site settings
author: Daniel Quillao
title: My Journey into Data Science
header-img: img/home-bg.png
email: quillaodaniel@gmail.com
copyright_name: Daniel Quillao
description: > # this means to ignore newlines until "baseurl:"
  Welcome!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dquillao

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
